---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "mcr.microsoft.com/windows:${MOLECULE_WIN_VER:-20H2}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    priveleged: false
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
